apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ignition-role-bind
subjects:
  - kind: ServiceAccount
    name: ignition-sa
roleRef:
  kind: Role
  name: ignition-role
  apiGroup: rbac.authorization.k8s.io